import type { Locale } from "./ui-types";

export const copy = {
  zh: {
    appName: "KnowledgeGraph",
    navGraph: "知识图谱",
    github: "GitHub",
    about: "关于",
    search: "搜索",
    searchPlaceholder: "搜索知识点，比如 TCP、进程、索引",
    searchResults: "搜索结果",
    noSearchResult: "没有匹配的知识点",
    aboutTitle: "关于 KnowledgeGraph",
    aboutLead: "KnowledgeGraph 是面向计算机基础学习者的可视化学习项目，用分类图谱、知识详情和交互模拟器组织抽象概念。",
    aboutSections: [
      ["项目目标", "把网络、操作系统、数据结构、数据库、后端工程和 AI Agent 等主题放进统一知识图谱，帮助学习者看到知识之间的连接。"],
      ["当前能力", "左侧分类切换专题图谱，顶部搜索快速定位知识点，图谱节点进入详情页，流程型知识点提供交互式模拟。"],
      ["内容结构", "每个分类包含一组核心知识点，知识点带难度、关系和学习入口，后续可以继续扩展更多详情页和模拟器。"],
    ],
    themeLight: "浅色",
    themeDark: "深色",
    lang: "中文",
    learningPath: "所需知识",
    fundamentals: "分类总览",
    categories: [
      ["network", "计算机网络"],
      ["os", "操作系统"],
      ["algorithm", "数据结构与算法"],
      ["mysql", "Mysql"],
      ["redis", "Redis"],
      ["rabbitmq", "RabbitMQ"],
      ["backend", "后端进阶"],
      ["docker", "Docker"],
      ["kubernetes", "Kubernetes"],
      ["agent", "Agent"],
    ],
    difficultyFilter: "难度筛选",
    difficulties: ["简单", "中等", "困难"],
    upgrade: "升级",
    focused: "当前聚焦",
    graphBoard: "画板类型",
    knowledgeBoard: "知识图谱",
    visualBoard: "可视化图谱",
    graphMode: "图谱范围",
    coreMode: "核心",
    allMode: "全部",
    canvasControls: "画布控制",
    zoomIn: "放大",
    zoomOut: "缩小",
    resetView: "重置视图",
    medium: "中等",
    tcpTitle: "TCP",
    tcpSummary: "可靠连接 · 三次握手 · 有序传输",
    prerequisites: "前置知识",
    related: "相关知识",
    categoryOverview: "分类概览",
    knowledgePoints: "知识点",
    sourceReferences: "参考来源",
    sourceDescription: "本分类知识点参考以下八股文和面试资料整理。",
    detailInfo: "知识点信息",
    explanation: "讲解",
    scenarioExamples: "典型问题",
    exampleProblems: "例题练习",
    learningOrder: "学习顺序",
    openReference: "打开来源",
    documentation: "文档",
    ipProtocol: "IP 协议",
    networkLayer: "网络层",
    udp: "UDP",
    connectionless: "无连接协议",
    handshake: "三次握手",
    viewDetail: "详情",
    breadcrumbGraph: "知识图谱",
    breadcrumbNetwork: "计算机网络",
    detailTitle: "TCP 三次握手",
    detailSubtitle: "建立连接，确认双方收发能力，同步初始序列号。",
    transportLayer: "传输层",
    reliable: "可靠传输",
    coreConcept: "核心概念",
    conceptBody: "TCP 先建立可靠连接，再开始传输数据。",
    consistency: "连接一致性",
    consistencyBody: "同步序列号",
    initialization: "资源初始化",
    initializationBody: "准备传输资源",
    handshakeSteps: "握手步骤",
    steps: [
      {
        title: "第一次握手：SYN",
        body: "客户端发送 SYN，声明 seq=x。",
        quote: "我想建立连接，我的初始序列号是 x。",
      },
      {
        title: "第二次握手：SYN-ACK",
        body: "服务端返回 SYN-ACK，声明 seq=y，确认 ack=x+1。",
        quote: "收到你的请求。我同意建立连接，我的序列号是 y。",
      },
      {
        title: "第三次握手：ACK",
        body: "客户端发送 ACK，确认 ack=y+1。",
        quote: "我知道你准备好了。连接建立成功。",
      },
    ],
    stateTable: "状态变化表",
    tableHeads: ["角色", "初始状态", "发送/接收", "最终状态"],
    tableRows: [
      ["Client", "CLOSED", "发送 SYN", "SYN-SENT"],
      ["Server", "LISTEN", "收 SYN，发 SYN-ACK", "SYN-RCVD"],
      ["Client", "SYN-SENT", "收 SYN-ACK，发 ACK", "ESTABLISHED"],
      ["Server", "SYN-RCVD", "收 ACK", "ESTABLISHED"],
    ],
    interactive: "交互式仿真",
    interactiveBody: "按步骤推进事件、报文或状态变化。",
    startSimulator: "开始模拟",
    openVisualBoard: "查看可视化图谱",
    visualTag: "可视化",
    visualizable: "可视化",
    visualizablePoints: "可视化知识点",
    visualizableIntro: "以下知识点适合通过流程、状态、路径或结构模拟理解。",
    visualPattern: "可视化类型",
    simulationMetrics: "观察指标",
    currentState: "当前状态",
    stepInsight: "理解重点",
    actorStates: "参与者状态",
    progress: "进度",
    contents: "本章目录",
    contentItems: [
      "核心概念",
      "握手步骤",
      "状态变化",
      "模拟器",
      "下一章",
    ],
    nextStep: "下一章节",
    dataTransfer: "TCP 数据传输",
    visualCaption: "连接生命周期",
    backDetail: "返回详情",
    simulatorTitle: "TCP 三次握手模拟器",
    reset: "重置",
    previousAction: "上一步",
    client: "客户端",
    server: "服务器",
    physicalLink: "物理链路",
    currentTask: "当前任务",
    actionPanel: "操作面板",
    feedback: "操作反馈",
    history: "历史记录",
    waitingFeedback: "等待操作反馈",
    waitingAction: "等待操作",
    tasks: [
      "发送第一个报文。",
      "返回确认报文。",
      "发送最终确认。",
      "连接建立完成，双方进入 ESTABLISHED 状态。",
    ],
    actions: ["发送 SYN", "发送 SYN-ACK", "发送 ACK"],
    invalid: "当前步骤请选择高亮操作。",
    feedbacks: [
      "客户端进入 SYN-SENT。",
      "服务端进入 SYN-RCVD。",
      "双方进入 ESTABLISHED。",
    ],
    historyItems: [
      "客户端发出 SYN (seq=x)",
      "服务端返回 SYN-ACK (seq=y, ack=x+1)",
      "客户端发出 ACK (ack=y+1)",
    ],
    timeline: ["SYN 发送", "SYN-ACK 确认", "ACK 确认", "ESTABLISHED"],
    complete: "完成",
    proAccess: "专业版",
    unlock: "更多图谱",
    privacy: "隐私政策",
    terms: "服务条款",
    feedbackLink: "反馈建议",
  },
  en: {
    appName: "KnowledgeGraph",
    navGraph: "Knowledge Graph",
    github: "GitHub",
    about: "About",
    search: "Search",
    searchPlaceholder: "Search topics, e.g. TCP, process, index",
    searchResults: "Search Results",
    noSearchResult: "No matching knowledge points",
    aboutTitle: "About KnowledgeGraph",
    aboutLead: "KnowledgeGraph is a visual learning project for computer science fundamentals, organizing abstract concepts with category graphs, knowledge details, and interactive simulators.",
    aboutSections: [
      ["Goal", "Put networks, operating systems, data structures, databases, backend engineering, and AI Agent topics into one connected knowledge graph."],
      ["Current Features", "Use the left sidebar to switch topic graphs, search from the top bar, open node details, and run interactive simulations for process-oriented topics."],
      ["Content Model", "Each category contains core knowledge points with difficulty, relationships, and learning entry points, ready for more detail pages and simulators."],
    ],
    themeLight: "Light",
    themeDark: "Dark",
    lang: "English",
    learningPath: "Required Knowledge",
    fundamentals: "Category Overview",
    categories: [
      ["network", "Computer Networks"],
      ["os", "Operating Systems"],
      ["algorithm", "Data Structures & Algorithms"],
      ["mysql", "Mysql"],
      ["redis", "Redis"],
      ["rabbitmq", "RabbitMQ"],
      ["backend", "Backend Advanced"],
      ["docker", "Docker"],
      ["kubernetes", "Kubernetes"],
      ["agent", "Agent"],
    ],
    difficultyFilter: "Difficulty Filter",
    difficulties: ["Easy", "Medium", "Hard"],
    upgrade: "Upgrade",
    focused: "Focused",
    graphBoard: "Board Type",
    knowledgeBoard: "Knowledge Graph",
    visualBoard: "Visual Graph",
    graphMode: "Graph Scope",
    coreMode: "Core",
    allMode: "All",
    canvasControls: "Canvas controls",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset view",
    medium: "Medium",
    tcpTitle: "TCP",
    tcpSummary: "Reliable connection · three-step handshake · ordered delivery",
    prerequisites: "Prerequisites",
    related: "Related",
    categoryOverview: "Category Overview",
    knowledgePoints: "Knowledge Points",
    sourceReferences: "References",
    sourceDescription: "Knowledge points in this category are organized from these interview and learning resources.",
    detailInfo: "Knowledge Info",
    explanation: "Explanation",
    scenarioExamples: "Typical Questions",
    exampleProblems: "Practice Problems",
    learningOrder: "Learning Order",
    openReference: "Open Reference",
    documentation: "Documentation",
    ipProtocol: "IP Protocol",
    networkLayer: "Network Layer",
    udp: "UDP",
    connectionless: "Connectionless",
    handshake: "Three-Way Handshake",
    viewDetail: "Details",
    breadcrumbGraph: "Knowledge Graph",
    breadcrumbNetwork: "Computer Networks",
    detailTitle: "TCP Three-Way Handshake",
    detailSubtitle: "Establish connection, verify both sides, sync sequence numbers.",
    transportLayer: "Transport Layer",
    reliable: "Reliable",
    coreConcept: "Core Concept",
    conceptBody: "TCP establishes a reliable connection before data transfer.",
    consistency: "Connection Consistency",
    consistencyBody: "Sync sequence numbers",
    initialization: "Resource Initialization",
    initializationBody: "Prepare transfer resources",
    handshakeSteps: "Handshake Steps",
    steps: [
      {
        title: "First Handshake: SYN",
        body: "Client sends SYN with seq=x.",
        quote: "I want to connect. My initial sequence number is x.",
      },
      {
        title: "Second Handshake: SYN-ACK",
        body: "Server returns SYN-ACK with seq=y and ack=x+1.",
        quote: "Request received. I accept and my sequence number is y.",
      },
      {
        title: "Third Handshake: ACK",
        body: "Client sends ACK with ack=y+1.",
        quote: "I know you are ready. The connection is established.",
      },
    ],
    stateTable: "State Transition",
    tableHeads: ["Role", "Initial State", "Send / Receive", "Final State"],
    tableRows: [
      ["Client", "CLOSED", "Send SYN", "SYN-SENT"],
      ["Server", "LISTEN", "Receive SYN, send SYN-ACK", "SYN-RCVD"],
      ["Client", "SYN-SENT", "Receive SYN-ACK, send ACK", "ESTABLISHED"],
      ["Server", "SYN-RCVD", "Receive ACK", "ESTABLISHED"],
    ],
    interactive: "Interactive Simulation",
    interactiveBody: "Step through events, packets, or state transitions.",
    startSimulator: "Start Simulation",
    openVisualBoard: "Open Visual Graph",
    visualTag: "Visual",
    visualizable: "Visualizable",
    visualizablePoints: "Visualizable Topics",
    visualizableIntro: "These topics are best understood through flow, state, path, or structure simulations.",
    visualPattern: "Visualization Type",
    simulationMetrics: "Signals to Watch",
    currentState: "Current State",
    stepInsight: "Key Insight",
    actorStates: "Actor States",
    progress: "Progress",
    contents: "Contents",
    contentItems: [
      "Core Concept",
      "Steps",
      "States",
      "Simulator",
      "Next",
    ],
    nextStep: "Next Chapter",
    dataTransfer: "TCP Data Transfer",
    visualCaption: "Connection lifecycle",
    backDetail: "Back to Detail",
    simulatorTitle: "TCP Handshake Simulator",
    reset: "Reset",
    previousAction: "Previous",
    client: "Client",
    server: "Server",
    physicalLink: "Physical Link",
    currentTask: "Current Task",
    actionPanel: "Action Panel",
    feedback: "Feedback",
    history: "History",
    waitingFeedback: "Waiting for feedback",
    waitingAction: "Waiting for action",
    tasks: [
      "Send the first packet.",
      "Return the confirmation packet.",
      "Send the final ACK.",
      "Connection established. Both sides are now ESTABLISHED.",
    ],
    actions: ["Send SYN", "Send SYN-ACK", "Send ACK"],
    invalid: "Choose the highlighted action for this step.",
    feedbacks: [
      "Client is SYN-SENT.",
      "Server is SYN-RCVD.",
      "Both sides are ESTABLISHED.",
    ],
    historyItems: [
      "Client sent SYN (seq=x)",
      "Server returned SYN-ACK (seq=y, ack=x+1)",
      "Client sent ACK (ack=y+1)",
    ],
    timeline: ["SYN Sent", "SYN-ACK Confirmed", "ACK Confirmed", "ESTABLISHED"],
    complete: "Complete",
    proAccess: "Pro Access",
    unlock: "More graphs",
    privacy: "Privacy",
    terms: "Terms",
    feedbackLink: "Feedback",
  },
} as const;

export type Copy = (typeof copy)[Locale];
